version: "3"
services:
  #web service
  #   web:
  #     container_name: tax-platform-client
  #     image: index.docker.io/mpaccione/tax-platform-client:latest
  #     deploy:
  #       restart_policy:
  #         condition: any
  #     ports:
  #       - 3000:3000

  client:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - "/app/node_modules"
      - "./:/app"
